### ISSUE TITLE
Add typescript types

### ISSUE THREAD

**Issue by vilterp** [tylingsoft/dagre-layout#1]
I'm adding a declaration to the DefinitelyTyped repo [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20257), which will allow the library to be used in a typechecked fashion, but evidently it's preferred if they're checked in to the package itself. I don't quite have time to do this; letting you know in case you do. Thanks for a useful library!

There are some instructions [here](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html).

Used in [CockroachDB](https://github.com/cockroachdb/cockroach/pull/18344); checked type declarations into our repo but would prefer to have them elsewhere.

**Comment by tylerlong** [comment]
I don't use TypeScript myself so I am afraid that I am unable to do it. Let's wait for a community PR :)

**Comment by vilterp** [comment]
Fair enough — the DefinitelyTyped PR got merged, so for the time being TypeScript users can `npm install @types/dagre-layout`.

**Comment by tylerlong** [comment]
Close it for now. Feel free to create a new issue if you have new ideas/suggestions.
