### ISSUE TITLE
What are the goals of this fork?

### ISSUE THREAD

**Issue by pcj** [tylingsoft/dagre-layout#2]
Happy to see people picking up the torch on this useful library.  My questions are:

1. What are the updates / differences between this and dagre or dagre-d3?

2. What was missing that you're working on?

Thanks

**Comment by tylerlong** [comment]
The is not specific goal for this project. The changes I have made:

- Upgrade all the dependencies
- Yarn instead of NPM
- Get rid of PhantomJS
- ES6 instead of ES5
- Use webpack instead of browserify
- Use JavaScript Standard Style
- Use Jest for testing

**Comment by pcj** [comment]
Thanks @tylerlong, you should put that in the README.

**Comment by tylerlong** [comment]
Added the information to readme.
